name: enmeshed_runtime_bridge
description: A bridge between the enmeshed TypeScript runtime and Dart.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/app
homepage: https://enmeshed.eu

environment:
  sdk: "^3.6.0"
  flutter: ">=3.27.0"

dependencies:
  device_info_plus: ^11.1.0
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.0
  logger: ^2.4.0
  path_provider: ^2.1.5
  cal_flutter_plugin:
    path: ../../../rust-crypto/flutter_plugin/


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: any

platforms:
  android:
  ios:
  windows:

flutter:
  assets:
    - assets/loki.js
    - assets/index.js
    - assets/cryptoBridge.js
