name: enmeshed_runtime_bridge
description: A bridge between the Enmeshed TypeScript runtime and Dart.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/cns-app
homepage: https://enmeshed.eu

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  device_info_plus: ^9.0.2
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  logger: ^1.4.0
  meta: any
  path_provider: ^2.0.13

dev_dependencies:
  connector_sdk: 1.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.1

platforms:
  android:
  ios:

flutter:
  assets:
    - assets/loki.js
    - assets/index.js
