name: enmeshed_runtime_bridge
description: A bridge between the enmeshed TypeScript runtime and Dart.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/app
homepage: https://enmeshed.eu

environment:
  sdk: "^3.8.1"
  flutter: ">=3.32.7"

dependencies:
  cal_flutter_plugin:
    git:
      url: https://github.com/nmshd/rust-crypto
      path: cal_flutter_plugin
      ref: 3e9fc88
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.3.0
  logger: ^2.6.0
  path_provider: ^2.1.5
  windows_notification: ^1.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: any

platforms:
  android:
  ios:
  windows:

flutter:
  assets:
    - assets/loki.js
    - assets/index.js
