name: integration_test_runner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  enmeshed_runtime_bridge: ^1.0.0
  enmeshed_types: ^1.0.0
  flutter:
    sdk: flutter
  logger: ^2.5.0
  cal_flutter_plugin:
    git:
      url: https://github.com/nmshd/rust-crypto.git
      path: flutter_plugin/
      ref: ca6548b

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
