name: connector_ui
description: A UI for the Enmeshed Connector.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  collection: any
  connector_sdk: 1.0.0
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  shared_preferences: ^2.0.20
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  dart_code_metrics: ^5.7.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.9.1

flutter:
  uses-material-design: true

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/icon-mac.png"

msix_config:
  display_name: Connector UI
  publisher_display_name: j&s-soft GmbH
  identity_name: de.enmeshed.connector_ui
  msix_version: 1.0.0.0
  logo_path: .\assets\images\icon.png
