name: enmeshed_types
description: Enmeshed Types.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/app
homepage: https://enmeshed.eu

environment:
  sdk: ^3.2.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: any

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  test: ^1.25.2
