name: enmeshed_types
description: Enmeshed Types.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/cns-app
homepage: https://enmeshed.eu

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  equatable: ^2.0.5
  meta: any
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.1
  test: ^1.21.0
