name: value_renderer_example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_i18n: ^0.34.0
  flutter_localizations:
    sdk: flutter
  intl: any
  value_renderer: 1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/i18n/
