name: connector_sdk
description: A Dart SDK for the Enmeshed Connector.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/app
homepage: https://enmeshed.eu

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.4.1
  enmeshed_types: 1.0.0
  meta: any

dev_dependencies:
  flutter_lints: ^3.0.1
