name: connector_sdk
description: A Dart SDK for the Enmeshed Connector.
version: 1.0.0
publish_to: none

repository: https://github.com/nmshd/cns-app
homepage: https://enmeshed.eu

environment:
  sdk: ^3.2.0

dependencies:
  dio: ^5.3.3
  enmeshed_types: 1.0.0
  meta: any

dev_dependencies:
  flutter_lints: ^2.0.3
