name: renderers
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.17.2
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_i18n: ^0.35.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  i18n_translated_text: ^1.0.1
  intl: any
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  value_renderer: 1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
