name: renderers
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: "^3.7.0"
  flutter: ">=3.29.0"

resolution: workspace

dependencies:
  collection: any
  enmeshed_types: 1.0.0
  flutter:
    sdk: flutter
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  i18n_translated_text: ^1.0.2
  intl: any
  logger: ^2.4.0
  url_launcher: ^6.3.1
  value_renderer: 1.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
